import type { Metadata } from "next"
import localFont from "next/font/local"
import "./globals.css"
import ThemeProvider from "./providers/theme-provider"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
})
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <ThemeProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} flex h-screen flex-col items-center justify-center p-4 text-foreground antialiased`}
        >
          {children}
        </body>
      </ThemeProvider>
    </html>
  )
}
